services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "${UI_PORT}:${UI_PORT}"
    env_file:
      - .env
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
      - ./shared:/shared
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - .env
    volumes:
      - ./user-service:/app
      - /app/node_modules
      - ./shared:/shared
  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
      dockerfile: Dockerfile.dev
    ports:
      - "${MATCHING_SERVICE_PORT}:${MATCHING_SERVICE_PORT}"
    env_file:
      - .env
    volumes:
      - ./matching-service:/app
      - /app/node_modules
      - ./shared:/shared
  question-service:
    container_name: question-service
    build:
      context: ./question-service
      dockerfile: Dockerfile.dev
    ports:
      - "${QUESTION_SERVICE_PORT}:${QUESTION_SERVICE_PORT}"
    env_file:
      - .env
    volumes:
      - ./question-service:/app
      - /app/node_modules
      - ./shared:/shared
  collaboration-service:
    container_name: collaboration-service
    build:
      context: ./collaboration-service
      dockerfile: Dockerfile.dev
    ports:
      - "${COLLABORATION_SERVICE_PORT}:${COLLABORATION_SERVICE_PORT}"
    env_file:
      - .env
    volumes:
      - ./collaboration-service:/app
      - /app/node_modules
      - ./shared:/shared
